apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: top-car-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: top-car-service
  template:
    metadata:
      labels:
        app: top-car-service
    spec:
      containers:
      - name: top-car-service
        image: top-car-service:latest
        ports:
        - containerPort: 8082
        env:        
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: db-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: db-password
        envFrom:        
        - configMapRef:
            name: app-settings
