apiVersion: v1
kind: Service
metadata:
  name: top-car-service
  labels:
    app: top-car-app
spec:
  type: ClusterIP
  selector:
    app: top-car-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
