apiVersion: v1
kind: Service
metadata:
  name: top-car-app-db-svc
  labels:
    app: top-car-app-db-svc
spec:  
  selector:
    app: top-car-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
